### ISSUE TITLE
Rename `gazetteer.json` to `mapbox-streets-gazetteer.json`?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/gazetteer#18]
Now that we're revamping the current gazetteer file to be specific to the Mapbox Streets vector tileset, maybe we should rename the file. Hopefully soon we'll also have one for Mapbox Terrain and Mapbox Satellite :)

Side note: why does this file have a .json extension and not a .geojson one?

@dasulit

**Comment by dasulit** [comment]
The possibilities are endless! +1 to `mapbox-streets-gazetteer.geojson`

**Comment by dasulit** [comment]
Seems like .json vs .geojson might be an npm thing ☹️  didn't dig too much but was getting errors with `main` being a .geojson file in package.json, I just switched back to .json to troubleshoot and everything worked as expected. Hmm.
