### ISSUE TITLE
export `getAll` function

### ISSUE THREAD

**Issue by dasulit** [mapbox/gazetteer#47]
It's weird that you need to know the name of gazetteers to use them, potentially we could also export a `gazetteer.getAll()`.

**Comment by tristen** [comment]
👋 @dasulit should this be closed? After https://github.com/mapbox/gazetteer/pull/52 gazetteers are exported as named objects.

**Comment by dasulit** [comment]
Yeah, this issue reflects an outdated suggestion. Thanks for the cleanup.
